### ISSUE TITLE
Adding devices with dns host name doesn't work

### ISSUE THREAD

**Issue by lhurt** [Moustachauve/WLED-Native-iOS#5]
As I have dhcp in my network for all device, it would be nice to have the option to add devices with their DNS name.

The device can be added but is shown as disconnected. No matter whether URL with Hostnamen or fully qualified.

Can you please check what I'm doing wrong?

**Comment by lhurt** [comment]
Are you @Moustachauve reading this or is the project abandoned?

**Comment by lhurt** [comment]
> @lhurt I work on this in my free time as a hobby. Sorry I have not been able to work on this in the past months.

Thanks for the information. I like the app a lot and I think it has a lot of potential. Hope you'll find time for it soon.

**Comment by FVierra27** [comment]
> @lhurt I work on this in my free time as a hobby. Sorry I have not been able to work on this in the past months.

I am also having the same problem. Cannot resolve using hostname.

**Comment by Moustachauve** [comment]
This should be fixed now since version 2.

**Comment by lhurt** [comment]
@Moustachauve 
Thanks for fixing it. There are is still an issue

When adding a new device manually the field for the address has the text "IP Address or URL". If you add a device with _http://some.address_, the device is shown as offline. The correct format is _some.adress_ which is either the FQDN or DN. It would be even more helpful if the protocol part of the entered address would be automatically cropped.
The description in the field inconsistent with the required data. It would be great if you could  add this presumably easy adjustment.

Thanks a log.

**Comment by Moustachauve** [comment]
That's a great suggestion, I'll add this for version 3!
